version: "3.9"
services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"
  worker:
    build:
      context: .
      dockerfile: docker/Dockerfile
    environment:
      - REDIS_URL=redis://redis:6379/0
    command: ["/bin/bash", "-lc", "scripts/run_worker.sh"]
    depends_on:
      - redis
    volumes:
      - ./:/workspace
      - ${IMAGES_DIR:-/tmp/images}:/data/images
      - ${TOOLBOX_REPO:-/opt/Aesthetics-Toolbox}:/opt/Aesthetics-Toolbox
      - ${OUT_DIR:-/workspace/out}:/workspace/out
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: ["gpu"]
